STATUS_LABEL_WIDTH = 86
STATUS_WRAP_LENGTH = 680
DETAIL_LABEL_WIDTH = 64

CONFIDENCE_CANVAS_SIZE = 120
CONFIDENCE_RING_WIDTH = 18
SUMMARY_MIN_WIDTH = 235
COMBINATION_CANVAS_SIZE = 86
COMBINATION_RING_WIDTH = 13

COLOR_SPAM = "#c0392b"
COLOR_HAM = "#27ae60"
COLOR_NEUTRAL = "#7f8c8d"
COLOR_RING_BACKGROUND = "#e5e5e5"
COLOR_TEXT_MUTED = "gray"
COLOR_TEXT_DEFAULT = "black"
